
name: Ammu Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Groot workflow
      context: .
      platforms: linux/amd64,linux/arm64
      tags: user/app:latest
      secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
      run: sudo apt update && sudo apt install git curl python3-pip ffmpeg -y && pip3 install -U pip && npm init -y && npm i --save-dev node@16 && npm config set prefix=$(pwd)/node_modules/node && export PATH=$(pwd)/node_modules/node/bin:$PATH && pip3 install -U -r requirements.txt && python3 -m main.py
   
     - name: loop Ammu workflow server
         continue-on-error: true
         run: 
              git clone https://github.com/tokyoworld/Ammuofficial  loop
              cd loop || exit 1
              echo $(date -u +%T%P) >> loop.txt
              git add loop.txt
              git commit -m "Ammu workflow : Loop $(date -u +%D-%T%P)"
              git push -q https://${{ secrets.GIT_TOKEN }}@github.com/tokyoworld/Ammuofficial HEAD:Ammu workflow
